# Generated by Django 5.1.5 on 2025-01-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
