# Generated by Django 5.1.5 on 2025-02-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_remove_bankdetails_basic_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='is_fresher',
            field=models.BooleanField(default=False),
        ),
    ]
